# Generated by Django 5.1.6 on 2025-02-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageCheck', '0001_initial'),
    ]

    operations = [
    ]
