# Generated by Django 5.1.6 on 2025-02-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageCheck', '0002_auto_20250208_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicines',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
